#!/usr/bin/env python
# encoding: utf-8

import inspect
import os
import subprocess
import sys

currentDir = os.path.dirname(os.path.realpath(
    os.path.abspath(inspect.getfile(inspect.currentframe()))))

projectDir = currentDir

# Add and parse arguments {{{
# -----------------------------------------------------------------------------
from argparse import ArgumentParser

parser = ArgumentParser()

parser.add_argument('builder', nargs='?', default='ninja')
parser.add_argument('-c', default='Release')

args, unknown_args = parser.parse_known_args()
# -----------------------------------------------------------------------------
# }}}

# Filter arguments {{{
# -----------------------------------------------------------------------------
args.c = args.c.strip()
# -----------------------------------------------------------------------------
# }}}

# Invoke Builder {{{
# -----------------------------------------------------------------------------
variandDir = os.path.join(projectDir, '.build', args.c)

command = "%s %s" % (args.builder,
      " ".join(unknown_args))

subprocess.call(command, cwd=variandDir, shell=True)
# -----------------------------------------------------------------------------
# }}}
