#!/usr/bin/env python
# encoding: utf-8

import inspect
import os
import shutil

currentDir = os.path.dirname(os.path.realpath(
    os.path.abspath(inspect.getfile(inspect.currentframe()))))

projectDir = currentDir

buildDir = os.path.join(projectDir, 'build')

if os.path.isdir(buildDir):
    shutil.rmtree(buildDir)

installDir = os.path.join(projectDir, 'install')

if os.path.isdir(installDir):
    shutil.rmtree(installDir)
